/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */

public class byaddress extends javax.swing.JFrame {
String metercode=" ",namme=" ",email=" ",address=" ",slash="----------------------------",payment=" ",payment2=" ",date=" ",taxes="";

    public byaddress() {
        initComponents();
        setSize(450, 425);
                setVisible(true);
        setLocationRelativeTo(null);
    }
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Enter the region");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 127, 30);

        textt.setBackground(new java.awt.Color(204, 204, 204));
        textt.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        textt.setForeground(new java.awt.Color(102, 0, 0));
        textt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttActionPerformed(evt);
            }
        });
        getContentPane().add(textt);
        textt.setBounds(20, 50, 130, 40);

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 110, 430, 230);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(279, 342, 101, 31);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setText("querry");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(65, 343, 97, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\importan papers\\pl2\\project\\im.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 440, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
              // TODO add your handling code here:
        objectt nn=new objectt();
        method o=new method();
        boolean check=false;
            
        try {
            // TODO add your handling code here:
            nn.file_write(nn.querry_address," ");
//            FileWriter fw = new FileWriter("D:\\importan papers\\pl2\\section\\operator\\build\\classes\\operator\\new and old\\querry_address.txt");
//               fw.write(" ");
//               fw.close();
           BufferedReader bb=nn.file_read(nn.info);
            //FileReader fr=new FileReader("D:\\importan papers\\pl2\\section\\operator\\build\\classes\\operator\\new and old\\info.txt");
            //BufferedReader bb=new BufferedReader(fr);
            //Scanner nn=new Scanner(fr);
            String struct;
            while((struct=bb.readLine())!=null)
            {
                if(textt.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"please enter the region" ,"the region is not valid", JOptionPane.ERROR_MESSAGE);
                check=true;
               nn.file_write(nn.querry_address," ");
                
                            BufferedReader br = nn.file_read(nn.querry_address);
                         jTextArea1.read(br,null);
                   
                        //new BufferedReader(reader);
                       
                 
                break;
            }
                
            
              else if(struct.contains(textt.getText().trim()))
                {
                    System.out.println("found");//for developers
                    check=true;
                    //nn.useDelimiter("[|]");
                    
                    //String x=nn.nextLine();
                    String [] a=struct.split("[|]");
                        metercode=a[0];
                        System.out.println(metercode);
                        namme=a[1];
                        System.out.println(namme);
                        email=a[2];
                        address=a[3];
                        method d=new method();
                d. file2(metercode,jTextArea1,a);}}
           /* FileWriter fw = new FileWriter("D:\\importan papers\\pl2\\section\\operator\\build\\classes\\operator\\new and old\\querry_address.txt");
               fw.write(" ");
               fw.close();*/
               
                        
        if(!check )
            {
                 JOptionPane.showMessageDialog(null,"the region is not correct" ," region is not correct", JOptionPane.ERROR_MESSAGE);
                 nn.file_write(nn.querry_address," ");
//                 FileWriter fww = new FileWriter("D:\\importan papers\\pl2\\section\\operator\\build\\classes\\operator\\new and old\\querry_address.txt");
//               fww.write(" ");
//               fww.close();
                 
               //FileReader reader=new FileReader("D:\\importan papers\\pl2\\section\\operator\\build\\classes\\operator\\new and old\\querry_address.txt");
                    BufferedReader br=nn.file_read(nn.querry_address);
                            //new BufferedReader(reader);
                    jTextArea1.read(br,null);
                    br.close(); 
            }      
        
    }
                    
                    
         catch (FileNotFoundException ex) {
            Logger.getLogger(byaddress.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(byaddress.class.getName()).log(Level.SEVERE, null, ex);
      
    }  
                                               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void texttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texttActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   path  c= new path();
              c.setVisible(true);
              c.show();
        this.dispose();
                        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(byaddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(byaddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(byaddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(byaddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new byaddress().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textt;
    // End of variables declaration//GEN-END:variables
}
