/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

/**
 *
 * @author Lenovo
 */
public class customer_interface extends javax.swing.JFrame {

    /**
     * Creates new form customer_interface
     */
    public customer_interface() {
        initComponents();
        setSize(420, 330);
                setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customer_menu_label = new javax.swing.JLabel();
        new_customer_ = new javax.swing.JButton();
        existing_customer_ = new javax.swing.JButton();
        c_exit_ = new javax.swing.JButton();
        c_back_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("electricity company");
        getContentPane().setLayout(null);

        customer_menu_label.setBackground(new java.awt.Color(204, 204, 204));
        customer_menu_label.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        customer_menu_label.setForeground(new java.awt.Color(204, 204, 204));
        customer_menu_label.setText("customer menu");
        getContentPane().add(customer_menu_label);
        customer_menu_label.setBounds(167, 13, 141, 22);

        new_customer_.setBackground(new java.awt.Color(204, 204, 204));
        new_customer_.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        new_customer_.setForeground(new java.awt.Color(102, 0, 0));
        new_customer_.setText("new customer");
        new_customer_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_customer_ActionPerformed(evt);
            }
        });
        getContentPane().add(new_customer_);
        new_customer_.setBounds(110, 80, 210, 31);

        existing_customer_.setBackground(new java.awt.Color(204, 204, 204));
        existing_customer_.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        existing_customer_.setForeground(new java.awt.Color(102, 0, 0));
        existing_customer_.setText("existing customer");
        existing_customer_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existing_customer_ActionPerformed(evt);
            }
        });
        getContentPane().add(existing_customer_);
        existing_customer_.setBounds(110, 150, 210, 31);

        c_exit_.setBackground(new java.awt.Color(204, 204, 204));
        c_exit_.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        c_exit_.setForeground(new java.awt.Color(102, 0, 0));
        c_exit_.setText("exit");
        c_exit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_exit_ActionPerformed(evt);
            }
        });
        getContentPane().add(c_exit_);
        c_exit_.setBounds(314, 225, 90, 31);

        c_back_.setBackground(new java.awt.Color(204, 204, 204));
        c_back_.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        c_back_.setForeground(new java.awt.Color(102, 0, 0));
        c_back_.setText("back");
        c_back_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_back_ActionPerformed(evt);
            }
        });
        getContentPane().add(c_back_);
        c_back_.setBounds(12, 225, 83, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\importan papers\\pl2\\project\\incandescent-bulbs-photo.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -3, 410, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_customer_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_customer_ActionPerformed
       new_customer_interface nci=new new_customer_interface();
        nci.show();
        this.dispose();
    }//GEN-LAST:event_new_customer_ActionPerformed

    private void existing_customer_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existing_customer_ActionPerformed
        old_customer_interface_next oci=new old_customer_interface_next();
        oci.show();
        this.dispose();
    }//GEN-LAST:event_existing_customer_ActionPerformed

    private void c_exit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_exit_ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_c_exit_ActionPerformed

    private void c_back_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_back_ActionPerformed
        main_interface m=new main_interface();
        m.show();
        this.dispose();
    }//GEN-LAST:event_c_back_ActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new customer_interface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c_back_;
    private javax.swing.JButton c_exit_;
    private javax.swing.JLabel customer_menu_label;
    private javax.swing.JButton existing_customer_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton new_customer_;
    // End of variables declaration//GEN-END:variables
}
