/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class invoice extends javax.swing.JFrame {
objectt nn=new objectt();
    /**
     * Creates new form invoice
     */
    public invoice() {
        initComponents();
        setSize(510, 430);
                setVisible(true);
        setLocationRelativeTo(null);
    }
 String metercode=" ",namme=" ",email=" ",address=" ",slash="----------------------------",payment=" ",payment2=" ",date=" ",taxes="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\importan papers\\pl2\\project\\incandescent-bulbs-photo.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("electricity company");
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Enter meter code");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 174, 25);

        textt.setBackground(new java.awt.Color(204, 204, 204));
        textt.setForeground(new java.awt.Color(102, 0, 0));
        textt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texttActionPerformed(evt);
            }
        });
        getContentPane().add(textt);
        textt.setBounds(200, 10, 152, 33);

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(102, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 400, 300);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 330, 80, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 0));
        jButton2.setText("print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 10, 87, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\importan papers\\pl2\\project\\im.jpeg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texttActionPerformed
        
    }//GEN-LAST:event_texttActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      boolean check=false;
        try {
            // TODO add your handling code here:
           BufferedReader bb=nn.file_read(nn.info);
            String struct;
            while((struct=bb.readLine())!=null)
            {
                 if(textt.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null,"please enter the meter code" ,"the meter code is not valid", JOptionPane.ERROR_MESSAGE);
                check=true;
              nn.file_write(nn.invoice," ");
                BufferedReader br=nn.file_read(nn.invoice);
                    jTextArea1.read(br,null);
                    br.close();
                break;
                
            }
                                
               else if(struct.contains(textt.getText())&&struct.contains("active"))
                {
                    
                    System.out.println("found");//for developers
                    JOptionPane.showMessageDialog(null,"the meter code is correct" ," METER CODE valid", JOptionPane.INFORMATION_MESSAGE);
                    check=true;
                     
                    String [] a=struct.split("[|]");
                        metercode=a[0];
                        System.out.println(metercode);
                        namme=a[1];
                        System.out.println(namme);
                        email=a[2];
                        address=a[3];
                  BufferedReader ll=nn.file_read(nn.collect_payments);
                String struct2;
            System.out.println("read");
                while((struct2=ll.readLine())!=null)
                {
                    if(struct2.contains(textt.getText().trim()))                    {
                        System.out.println("found 2");
                        String [] b=struct2.split("[|]");
                        payment=b[1];
                        System.out.println(payment);
                        payment2=b[2];
                        taxes=b[3];
                        date=b[4];
                       String write="\t\tINVOICE"+"\n\nDate of payment:"+date+"\ncustomer name: "+namme+"\ncustomer address :"+address+"\ncustomer country:egypt\ncustomer email :"+email+"\n"+slash+"\nmeter code :"+metercode+"\n reading:"+payment+"\n taxes:"+taxes+"\n total payment:"+payment2+"\n"+slash+slash+slash+"\n\n";
                         nn.file_write(nn.invoice,write);
                     BufferedReader br=nn.file_read(nn.invoice);
                    jTextArea1.read(br,null);
                    br.close();
                }}
                    if(!check)
                    {
                        JOptionPane.showMessageDialog(null,"this meter code has no payment or unactive" ,"error", JOptionPane.ERROR_MESSAGE);
                 nn.file_write(nn.invoice," ");
                 BufferedReader br=nn.file_read(nn.invoice);
                    jTextArea1.read(br,null);
                    br.close(); 
                    }
                    
                }
              
                        
                    }
            if(!check )
            {
                 JOptionPane.showMessageDialog(null,"the meter code is not correct" ," METER CODE is not valid", JOptionPane.ERROR_MESSAGE);
                 nn.file_write(nn.invoice," ");
                 BufferedReader br=nn.file_read(nn.invoice);
                    jTextArea1.read(br,null);
                    br.close(); 
            }      
                } catch (IOException ex) {
            Logger.getLogger(invoice.class.getName()).log(Level.SEVERE, null, ex);
        }
            
                    
                  

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        path  c= new path();
              c.setVisible(true);
              c.show();
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new invoice().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textt;
    // End of variables declaration//GEN-END:variables
}
